[package]
name = "tetris"
version = "0.1.0"
authors = ["John Stone <coleslaw.john@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17.3"
rand = "0.7.3"